## Python Assignment:Data Structures,Functions,Numpy&Pandas

##### 1.Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

###### Section A: Data Structures & Control Structures

In [1]:
### list of 5 integers
list1=[2,4,6,8,10]

In [2]:
### index
### the index is used to identify the index/position of the certain element
list1.index(8)

3

In [3]:
### append
### it is used  to add a single element to the end of the list
list1.append(12)

In [4]:
list1

[2, 4, 6, 8, 10, 12]

In [5]:
### remove
### it is used to remove the first occurance of a specific value from the list
list1.remove(2)

In [6]:
list1

[4, 6, 8, 10, 12]

In [7]:
### insert
### it is used to add an element at a specific position in the list
list1.insert(2,14)

In [8]:
list1

[4, 6, 14, 8, 10, 12]

In [9]:
### sort
### it is used to sort the elements in list in ascending or descending order
list1.sort(reverse=False)

In [10]:
list1

[4, 6, 8, 10, 12, 14]

In [11]:
list2=[5,10,17,20]

In [12]:
### extend
### used to add all the elements of another list to the end of the current list
list1.extend(list2)

In [13]:
list1

[4, 6, 8, 10, 12, 14, 5, 10, 17, 20]

In [14]:
### count
### used to check the number of times a specific element appears in the list
list1.count(10)

2

In [15]:
#### pop
### this is used to remove an element at a specified index from the list
list1.pop(6)
list1

[4, 6, 8, 10, 12, 14, 10, 17, 20]

In [16]:
### clear
### this method clears all elements from the list
list1.clear()
list1

[]

#### 2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [17]:
### creating a tuple
tuple1=('Durgha','Sarath','Arha')
tuple1

('Durgha', 'Sarath', 'Arha')

In [18]:
### we cannot change the elements in tuple,tuple is immutable so we have to convert tuple into list then we can change the element then again convert into tuple
## now i am changing tuple into list
list1=list(tuple1)

In [19]:
### now changing the second name 
list1[1]=('Yadhu')

In [20]:
### now changing list to tuple
tuple1=tuple(list1)

In [21]:
tuple1

('Durgha', 'Yadhu', 'Arha')

#### 3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [22]:
### creating a set with duplicate values
set={2,2,4,5,4,6,8}

In [23]:
set

{2, 4, 5, 6, 8}

In [24]:
### it is a property of sets in python that it  only store uniques elements..that is why even after creating a set with duplicate values it gave the output with unique elements

#### 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [25]:
### creating a dictionary
dict1={'Name':['Sandhya','Meivizhi','Nabeeha','panda','samson'],'Age':[22,23,24,22,21],'location':['bengaluru','pune','chennai','bengaluru','mumbai']}

In [26]:
dict1

{'Name': ['Sandhya', 'Meivizhi', 'Nabeeha', 'panda', 'samson'],
 'Age': [22, 23, 24, 22, 21],
 'location': ['bengaluru', 'pune', 'chennai', 'bengaluru', 'mumbai']}

In [27]:
### update the age
dict1['Age']=[21,23,24,22,22]

In [28]:
### adding a new key email
dict1['Email']=['sandhyam@gmail.com','mei2002@gmail.com','nabee23@gmail.com','2003panda@gmail.com','samson22@gmail.com']

In [29]:
dict1

{'Name': ['Sandhya', 'Meivizhi', 'Nabeeha', 'panda', 'samson'],
 'Age': [21, 23, 24, 22, 22],
 'location': ['bengaluru', 'pune', 'chennai', 'bengaluru', 'mumbai'],
 'Email': ['sandhyam@gmail.com',
  'mei2002@gmail.com',
  'nabee23@gmail.com',
  '2003panda@gmail.com',
  'samson22@gmail.com']}

In [30]:
### to get it in a dataframe
import pandas as pd

In [31]:
df=pd.DataFrame(dict1)
df

       Name  Age   location                Email
0   Sandhya   21  bengaluru   sandhyam@gmail.com
1  Meivizhi   23       pune    mei2002@gmail.com
2   Nabeeha   24    chennai    nabee23@gmail.com
3     panda   22  bengaluru  2003panda@gmail.com
4    samson   22     mumbai   samson22@gmail.com

#### 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [32]:
age=int(input("Enter Your Age"))
if age>=18:
    print("Good!you are eligible to vote")
else:
    print("not  Eligibile to Vote")

Enter Your Age 23

Good!you are eligible to vote

##### 6. Given a 'marks' variable, print the grade: - 90 and above: 'A' - 75–89: 'B' - 50–74: 'C' - Below 50: 'Fail'

In [33]:
marks=int(input('Enter your mark'))
if marks>=90:
    print('A grade')
elif marks>=75:
     print('B grade')
elif marks>=50:
     print('C grade')
else:
    print('fail')

Enter your mark 80

B grade

#### 7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [34]:
num=int(input('Enter the number'))
if num>0:
    if num%2==0:
        print(num,'is positive and even')
    else:
        print(num,'is positive but not even')
else:
    if num==0:
        print('numberis zero')
    else:
        print(num,'is negative')

Enter the number 2

2 is positive and even

### Section B: Numpy

#### 8. Create: - A scalar using np.array(5) - A 1D array with values 1 to 5 - A 2D array (2x3) with values from 10 to 60 in steps of 10

In [35]:
import numpy as np

In [36]:
scalar=np.array(5)
print(scalar)

5

In [37]:
### creating one dimensional array
one_dim=np.arange(1,6)
one_dim

array([1, 2, 3, 4, 5])

In [38]:
one_dim.ndim

1

In [39]:
### creating two dimensional array
two_dim=np.arange(10,70,10).reshape(2,3)
two_dim

array([[10, 20, 30],
       [40, 50, 60]])

In [40]:
two_dim.shape

(2, 3)

In [41]:
two_dim.ndim

2

#### 9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [42]:
nump_arr=np.random.randint(0,100,size=(4,4))
nump_arr

array([[94, 71, 22, 46],
       [97, 53, 68, 55],
       [39, 18,  6, 62],
       [16, 71, 50,  1]], dtype=int32)

#### 10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [43]:
array=np.random.randint(0,100,size=(3,3))
array

array([[40, 31, 67],
       [91, 59, 25],
       [75, 98, 77]], dtype=int32)

In [44]:
df_arr=pd.DataFrame(array,columns=(['A','B','C']))
df_arr

    A   B   C
0  40  31  67
1  91  59  25
2  75  98  77

### Section C: Exploring Pandas

#### 11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then: - Use .info(), .describe() - Select 'Name' and 'City' columns - Drop 'City' column - Fill any missing values in 'Salary' column with the mean - Remove any duplicate row

In [45]:
### creating a dataframe
data={'Name': ['Sandhya', 'Meivizhi', 'Nabeeha', 'Panda', 'Samson','Sanju','Durgha','Nandana','Nikhil','Yadhu'],
 'Age': [21, 23, 24, 22, 22,30,20,22,25,24],
 'City': ['bengaluru', 'pune', 'chennai', 'bengaluru', 'mumbai','delhi','kochi','hyderabad','jaipur','mumbai'],
 'Salary': [50000,80000,30000,np.nan,40000,50000,70000,np.nan,30000,50000]}
df_data=pd.DataFrame(data)
df_data

       Name  Age       City   Salary
0   Sandhya   21  bengaluru  50000.0
1  Meivizhi   23       pune  80000.0
2   Nabeeha   24    chennai  30000.0
3     Panda   22  bengaluru      NaN
4    Samson   22     mumbai  40000.0
5     Sanju   30      delhi  50000.0
6    Durgha   20      kochi  70000.0
7   Nandana   22  hyderabad      NaN
8    Nikhil   25     jaipur  30000.0
9     Yadhu   24     mumbai  50000.0

In [46]:
## get information
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [47]:
df_data.describe()

             Age        Salary
count  10.000000      8.000000
mean   23.300000  50000.000000
std     2.790858  17728.105209
min    20.000000  30000.000000
25%    22.000000  37500.000000
50%    22.500000  50000.000000
75%    24.000000  55000.000000
max    30.000000  80000.000000

In [48]:
df_data[['Name','City']]

       Name       City
0   Sandhya  bengaluru
1  Meivizhi       pune
2   Nabeeha    chennai
3     Panda  bengaluru
4    Samson     mumbai
5     Sanju      delhi
6    Durgha      kochi
7   Nandana  hyderabad
8    Nikhil     jaipur
9     Yadhu     mumbai

In [49]:
### removing city from dataframe
df_data=df_data.drop('City',axis=1)
df_data

       Name  Age   Salary
0   Sandhya   21  50000.0
1  Meivizhi   23  80000.0
2   Nabeeha   24  30000.0
3     Panda   22      NaN
4    Samson   22  40000.0
5     Sanju   30  50000.0
6    Durgha   20  70000.0
7   Nandana   22      NaN
8    Nikhil   25  30000.0
9     Yadhu   24  50000.0

In [50]:
### missing values
df_data.isnull().sum()

Name      0
Age       0
Salary    2
dtype: int64

In [51]:
### fill missing values in salary with mean
df_data['Salary']=df_data['Salary'].fillna(df_data['Salary'].mean())

In [52]:
df_data

       Name  Age   Salary
0   Sandhya   21  50000.0
1  Meivizhi   23  80000.0
2   Nabeeha   24  30000.0
3     Panda   22  50000.0
4    Samson   22  40000.0
5     Sanju   30  50000.0
6    Durgha   20  70000.0
7   Nandana   22  50000.0
8    Nikhil   25  30000.0
9     Yadhu   24  50000.0

In [53]:
df_data=df_data.drop_duplicates()
## the final data frame
df_data

       Name  Age   Salary
0   Sandhya   21  50000.0
1  Meivizhi   23  80000.0
2   Nabeeha   24  30000.0
3     Panda   22  50000.0
4    Samson   22  40000.0
5     Sanju   30  50000.0
6    Durgha   20  70000.0
7   Nandana   22  50000.0
8    Nikhil   25  30000.0
9     Yadhu   24  50000.0